### ISSUE TITLE
Sandbox: CSS module handling

### ISSUE THREAD

**Issue by mpeterdev** [near/react-on-chain#274]
```[tasklist]
### Tasks
- [ ] switch sidebar `styles.css` → `module.css`
- [ ] update our example code imports to use component name in CSS imports e.g. `./HelloWorld.module.css`
- [ ] automatically update css import on component rename
```

**Comment by mpeterdev** [comment]
this support is valuable for getting to the point where we can fully recommend a local development flow backed by github

**Comment by calebjacob** [comment]
As we're supporting the goal of 500 full time NEAR devs, it'll be critical to make it easy for devs to setup a local development flow that publishes via GitHub actions. The sandbox is great for tinkering, but any serious projects need to support collaboration and versioning through `git`.
